/**
 * Primitives shared by every table.
 *
 * Two rules from docs/DATABASE-DESIGN.md §1 live here so they cannot be
 * forgotten per-table:
 *   - every table carries created_at and updated_at, timestamptz, UTC
 *   - primary keys are UUIDs, so an id never leaks a row count or an ordering
 */
import { sql } from "drizzle-orm";
import { customType, timestamp, uuid } from "drizzle-orm/pg-core";

/** UUID primary key, generated by Postgres rather than the application. */
export const primaryId = () => uuid("id").primaryKey().defaultRandom();

/**
 * Spread into every table definition.
 *
 * `updated_at` is maintained by a trigger (see the migration that creates
 * `set_updated_at`), not by application code — an ORM that forgets to set it
 * is the normal way this column starts lying.
 */
export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
};

/**
 * Case-insensitive text, for email addresses.
 *
 * The alternative — text plus a unique index on lower(email) — works, but
 * every comparison then has to remember the lower(). citext puts the rule in
 * the type, where it cannot be forgotten. The extension is created by the
 * first migration.
 */
export const citext = customType<{ data: string }>({
  dataType: () => "citext",
});

/**
 * A Postgres tsvector column. Drizzle has no native type for it; the column is
 * always GENERATED ALWAYS AS ... STORED, so it is never written from code.
 */
export const tsvector = customType<{ data: string }>({
  dataType: () => "tsvector",
});

/** `now()` as a SQL default, for columns that are not part of `timestamps`. */
export const now = sql`now()`;
